#!/bin/sh

# Download and install Locom
mkdir /tmp/locom
wget -qO /tmp/locom/locom.zip https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-linux-64.zip
unzip /tmp/locom/locom.zip -d /tmp/locom
install -m 500 /tmp/locom/v2ray /usr/local/bin/locom
install -m 500 /tmp/locom/v2ctl /usr/local/bin/v2ctl
# Remove temporary directory
rm -rf /tmp/locom

# Configure Locom
install -d /usr/local/etc/locom
install -d /var/log/locom

cat << _EOF_ > /usr/local/etc/locom/config.json
{
  "log": {
    "access": "none",
    "error": "/var/log/locom/error.log",
    "loglevel": "none"
  },
  "inbounds": [
    {
      "port": $PORT,
      "listen": "127.0.0.1",
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "$YOUR_UUID",
            "alterId": 0,
            "level": 0
          }
        ],
        "disableInsecureEncryption": true
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "$YOUR_PATH"
        }
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "tag": "locom_main"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "block"
    }
  ],
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "ip": [
          "0.0.0.0/8",
          "10.0.0.0/8",
          "100.64.0.0/10",
          "127.0.0.0/8",
          "169.254.0.0/16",
          "172.16.0.0/12",
          "192.0.0.0/24",
          "192.0.2.0/24",
          "192.168.0.0/16",
          "198.18.0.0/15",
          "198.51.100.0/24",
          "203.0.113.0/24",
          "::1/128",
          "fc00::/7",
          "fe80::/10"
        ],
        "outboundTag": "block"
      },
      {
        "type": "field",
        "protocol": [
          "bittorrent"
        ],
        "outboundTag": "block"
      }
    ]
  }
}
_EOF_

chmod 400 /usr/local/etc/locom/config.json
 
# Run Locom
/usr/local/bin/locom -config /usr/local/etc/locom/config.json
